[project]
name = "lecture-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.124.2",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.38.0",
]
